FROM UBUNTU:18.04
FROM node:14
RUN NPM install --global yarn
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
RUN yarn add express
RUN npm install -g prisma
RUN npx prisma generate
RUN npm i @prisma/client

COPY . .
EXPOSE 3000
CMD ["npm", "start"]